/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ac3509",
        "on-primary": "#ffffff",
        "primary-container": "#ff7043",
        "on-primary-container": "#641800",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59f",
        "on-primary-fixed": "#3a0a00",
        "on-primary-fixed-variant": "#852300",
        "secondary": "#546067",
        "on-secondary": "#ffffff",
        "secondary-container": "#d7e4ec",
        "on-secondary-container": "#5a666d",
        "secondary-fixed": "#d7e4ec",
        "secondary-fixed-dim": "#bbc8d0",
        "on-secondary-fixed": "#111d23",
        "on-secondary-fixed-variant": "#3c494f",
        "tertiary": "#5d5f5f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9b9c9c",
        "on-tertiary-container": "#323434",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#59413a",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#ac3509",
        "outline": "#8d7169",
        "outline-variant": "#e0bfb6",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "inverse-primary": "#ffb59f",
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container": "1200px",
      },
      boxShadow: {
        "editorial": "0 20px 40px -15px rgba(0, 0, 0, 0.04)",
        "card": "0 4px 20px rgba(0, 0, 0, 0.04)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "fade-in": "fade-in 0.4s ease-out forwards",
      },
    },
  },
  plugins: [],
}
